### ISSUE TITLE
java.lang.AbstractMethodError after upgrade to latest TestNG plugin

### ISSUE THREAD

**Issue by jodzga** [cbeust/testng-eclipse#248]
### Expected behaviour
Tests are run

### Actual behaviour
Exception is thrown

### Steps to reproduce
1. Right click on a test class -> run as -> TestNG test
2. exception shows up in console:

java.lang.AbstractMethodError: org.testng.remote.support.RemoteTestNG6_9_7$DelegatingTestRunnerFactory.newTestRunner(Lorg/testng/ISuite;Lorg/testng/xml/XmlTest;Ljava/util/List;)Lorg/testng/TestRunner;
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:562)
	at org.testng.SuiteRunner.init(SuiteRunner.java:157)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:111)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1245)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1232)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1086)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)

### Running Configuration
* Plugin Version: 6.9.12.201604040524 (I upgraded to latest beta because to check if it was fixed there)
* (Optional) Plugin Git Revision: 
  (Since 6.9.11, you can get the plugin git revision via navigating "About Eclipse -> 'Installation Details' at left bottom -> 'Configuration' tab -> scroll down to '*** TestNG for Eclipse Details:' portion ")
* (Optional) Operating System:

**Comment by missedone** [comment]
hi @jodzga 
what's the testng version used at runtime?
could you double check is there any multi org.testng.TestNG classes on your classpath?

thanks

**Comment by jodzga** [comment]
That was it - I was pulling this dependency from another project.
Thanks!

**Comment by missedone** [comment]
good to know @jodzga 

however, i think there is still an issue in TestNG Eclipse plugin (actually in testng-remote) which suppose to correctly recognize the runtime testng version even there could be multi testng jars (or, TestNG classes) on the classpath.
my suspicion is it could be not the same classloader which running the testng cases as the one used for detecting the runtime testng version.

so we still need keep an eye on this ticket.

**Comment by missedone** [comment]
hi @jodzga 
could you share a small sample project to reproduce it?
thanks

**Comment by juherr** [comment]
@missedone I have a similar issue on a fresh eclipse install with testng project itself (imported by gradle):

```
java.lang.AbstractMethodError: org.testng.remote.support.RemoteTestNG6_5$DelegatingTestRunnerFactory.newTestRunner(Lorg/testng/ISuite;Lorg/testng/xml/XmlTest;Ljava/util/Collection;Ljava/util/List;)Lorg/testng/TestRunner;
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:594)
	at org.testng.SuiteRunner.init(SuiteRunner.java:168)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:117)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1339)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1326)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1180)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
```

Eclipse: Mars.2 Release (4.5.2)
TestNG plugin: 6.9.11.201604020423

**Comment by juherr** [comment]
And with the "beta" version (6.9.12.201606120617)

```
Exception in thread "main" java.lang.RuntimeException: Can't recognize the TestNG version on classpath. 
	at org.testng.remote.RemoteTestNG.getTestNGVersion(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:39)
```

**Comment by missedone** [comment]
it works for me with testng imported by Maven plugin, i don't think there should be any difference with Gradle plugin, anyway, i will install gradle and have a try :)

**Comment by missedone** [comment]
hi @juherr 
the issue is the snapshot versions was not correctly handled when parsing then into Version object. now fixed in https://github.com/testng-team/testng-remote/blob/3466fa04983051173bcf8d3d2dd4eceda7ab1fda/remote/src/main/java/org/testng/remote/RemoteTestNG.java#L78

**Comment by juherr** [comment]
I confirm, it works well with 6.9.12.201606220648 :+1:

**Comment by vassassins** [comment]
I am unable to run after after updating testng plugin 
Eclipse oxygen 2.0

Below script:

<package Data;

import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class Configuration 
{
      @DataProvider(name = "data-provider")
public Object[][] dataProviderMethod()
      {
	return new Object[][]
			{
		{"data-one"},
		{"data-two"},	
	};
		
}
@Test(dataProvider = "data-provider")
public void testMethod(String data)
{
    System.out.println("Data Provided by Data Provider is: "+data);
}
}>

Refer below for error logs

<[RemoteTestNG] detected TestNG version 6.13.1
java.lang.NoSuchMethodError: org.testng.remote.support.RemoteTestNG6_12.initializeEverything()V
	at org.testng.remote.support.RemoteTestNG6_12.initialize(RemoteTestNG6_12.java:22)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:97)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
>

Request you to kindly look into same. 
![data](https://user-images.githubusercontent.com/33202218/34865664-997de97e-f79f-11e7-8851-808359de86a6.png)

**Comment by missedone** [comment]
@vassassins, what's in "Referenced Libraries", i guess there's duplicate old TestNG classes and being loaded first

**Comment by JAYASGIT** [comment]
Thanks all.. even im facing the same problem it worked for me too

**Comment by sulaimaan26** [comment]
I think now it is occuring in 7.1.0.Find in the below screenshot.Works fine for version 6.14.3
![image](https://user-images.githubusercontent.com/49139974/74643019-a7e4d900-5139-11ea-88f5-a7b0ce9df88e.png)

**Comment by dramer** [comment]
I have the same problem on my mac.  Eclipse Oxygen

Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200



  TestNG	6.9.12.201607091356	org.testng.eclipse.feature.group	Cedric Beust


  TestNG P2 Feature	7.1.0.r202001120626	org.testng.p2.feature.feature.group	TestNG Team


I would think there would be a TestNG version 7 that would be installed?


Thank you for the help

**Comment by missedone** [comment]
Could you check there only one testng on your classpath?

**Comment by dramer** [comment]
My Windows 10 laptop has TestNG 7.0.0 installed and my windows 8 and mac has 6.10

  TestNG	7.0.0.201908240652	org.testng.eclipse.feature.group	Cedric Beust

What is the correct way to install TestNG 7 for eclipse?

**Comment by missedone** [comment]
@dramer , testng eclipse plugin 7.0.0 is OK.
i'm saying could you confirm there's only one testng on your classpath, you can add JVM arg `-verbose:class` to print out all the classes being loaded. 
check if it's the right testng from right location being loaded.

thanks

**Comment by dramer** [comment]
POM file is TestNG 7 but my elcipse testNg is 6.10, I'm trying to upgrade Eclipse to testNG 7.0. Having issues following the readme in GIT.  Says there is something missing. I will try again tonight.

**Comment by dramer** [comment]
I ran java -verbose:class on my windows 10 box and that only showed me java an sun packages loaded there is no testNg listed.  I'm going to type from the command echo %classpath%

**Comment by missedone** [comment]
@dramer ,  if you want to use testng-7.0, yes, you need to upgrade the testng eclipse plugin to 7.0+ as well.
pls let me know if you have issue.

**Comment by dramer** [comment]
@missedone  that is what I'm trying to do on my Windows 8 laptop.  I uninstalled testNG 6.10/9 then tried to install eclipse version 7.1, then tried 7.0 and it always fails with this error

Your original request has been modified.
  "Guava: Google Core Libraries for Java" is already installed, so an update will be performed instead.
Cannot complete the install because one or more required items could not be found.
  Software being installed: TestNG 7.1.0.202003090500 (org.testng.eclipse.feature.group 7.1.0.202003090500)
  Missing requirement: TestNG Eclipse Support 7.1.0.202003090500 (org.testng.eclipse 7.1.0.202003090500) requires 'bundle org.eclipse.jdt.launching 3.10.0' but it could not be found
  Cannot satisfy dependency:
    From: TestNG 7.1.0.202003090500 (org.testng.eclipse.feature.group 7.1.0.202003090500)
    To: org.testng.eclipse [7.1.0.202003090500]

**Comment by missedone** [comment]
@dramer 

> Missing requirement: TestNG Eclipse Support 7.1.0.202003090500 (org.testng.eclipse 7.1.0.202003090500) requires 'bundle org.eclipse.jdt.launching 3.10.0' but it could not be found

what's the eclipse version are you using? use may use newer version like eclipse 2019, 2020, etc.

**Comment by dramer** [comment]
@missedone  I was running older version of Eclipse..... upgraded and all works great.... sorry for the inconvenience !!!!!

**Comment by interviewBubble** [comment]
Tips:
1. if you are using an older version of eclipse then use older version of testNG
2. for new version use current testNG releases.

**Comment by priyankasapireddy** [comment]
> @vassassins, what's in "Referenced Libraries", i guess there's duplicate old TestNG classes and being loaded first

Im facing the same issue can you help me what to do for this ?
